FROM mcr.microsoft.com/devcontainers/base:debian

# RUN apt update && \
#     apt install -y --no-install-recommends \
#     ca-certificates \
#     curl \
#     &&
#     apt clean

# RUN curl -LsSf https://astral.sh/uv/install.sh | sh

# COPY ./.python-version ./pyproject.toml ./
# RUN uv sync
